### ISSUE TITLE
Decoupled Abstraction Layer For ORMs/ODMs

### ISSUE THREAD

**Issue by mcclayton** [procore-oss/blueprinter#153]
In general, I'd like to come up with a way to decouple Blueprinter from frameworks, ORMs/ODMs, etc. that would be nice for Blueprinter to support, but don't really make sense for Blueprinter to directly support out of the box.

i.e. Mongoid: https://github.com/procore/blueprinter/pull/150

An example of this would be that Blueprinter currently directly supports Active Record.
I'd like to think through an architecture, specifically for the ORMs/ODMs where we can decouple ourselves and make Active Record a configurable default, similar to how we support https://github.com/procore/blueprinter#oj.

**Comment by jacquescrocker** [comment]
Would love the ability to use this with Sequel also. I like the model of sister gems for compatibility. In the meantime I'm just monkey patching `array_like?`. Very suboptimal but it beats forking just to override a single line in the gem. 

Having native support for this would be huge
