### ISSUE TITLE
Create swagger (OpenAPI) definitions from views

### ISSUE THREAD

**Issue by dlcarter** [procore-oss/blueprinter#21]
It would be really cool, and helpful, if we had a way to be able to generate OpenAPI/swagger definition specs (namespaced by views, if they have one) from individual blueprints.

This will likely require more definition than we're used to giving these fields, like data type, etc. (Adding this may be helpful anyways)

**Comment by toobulkeh** [comment]
I could see the reverse being useful as well -- part of a Swagger CodeGen plugin!

**Comment by toobulkeh** [comment]
Here is a ruby-specific DSL for generating Swagger docs we've used recently:
https://github.com/domaindrivendev/rswag
