### ISSUE TITLE
Implement support for OpenAPI Data Types

### ISSUE THREAD

**Issue by dlcarter** [procore-oss/blueprinter#22]
We should implement a `type` (or similar) attribute on fields that corresponds to the OpenAPI spec data types.

The benefits are numerous, but notably:
- We can more intelligently decide how to serialize primitives
- It can empower direct OpenAPI spec generation (re: https://github.com/procore/painted-rabbit/issues/21)

**Comment by WithoutLegkiyMaxim** [comment]
I did this as part of monkeypatch for work needs, if relevant I can make a pull request

**Comment by dlcarter** [comment]
That would be great!

**Comment by timbroder** [comment]
@max-did-it were you able to open one?

**Comment by Drowze** [comment]
Can we reopen this issue? I'd love to see Blueprinter generating json schemas out of blueprint definitions and I could definitely help on this.

What kind of signature would we expect? @max-did-it would it be possible for you to share how the public API of your monkey-patch looked like?
