### ISSUE TITLE
Not able to use transformer when it is in included view

### ISSUE THREAD

**Issue by bhooshiek-narendiran** [procore-oss/blueprinter#225]
```
view :skeleton do
    include_view :summary
    excludes :actors, :ticket_id
  end

  view :summary do
    field :actors_response_info, name: :actors
    transform FieldTransformer
  end

```
Here when I directly use the view: summary then the FieldTransformer is working. But I can't able to use the same transformer when it is included in another view. Like if view: skeleton is called, the FieldTransformer is not working. This is because we are not taking the included views transformer while rendering the output. 
Can I raise a pr for this one?

**Comment by adamwells** [comment]
@bhooshiek-narendiran Good find, thank you - definitely feel free to open a PR to solve this.

**Comment by bhooshiek-narendiran** [comment]
Thanks, @adamwells Will do.

**Comment by aarona** [comment]
Could really use this. Would be great if someone could do a code review and accept this PR. @bhooshiek-narendiran, thanks for fixing this btw.

**Comment by cooperka** [comment]
Thanks for the PR @bhooshiek-narendiran!

Separate but related issue: views should inherit transformers from the base class but they do not. This is demonstrated by a new PR https://github.com/procore/blueprinter/pull/247. It is unfortunately **not** fixed by your change.

I wonder if we could make a generic fix for both issues... I don't currently have time to dig deeper but wanted to at least share these preliminary findings here (a workaround for me is to simply re-include the transformer in every single view, so that's what I'm doing until I have time to help with this proper fix).

**Comment by bhooshiek-narendiran** [comment]
HI @cooperka! Can you elaborate me the above issue with an example? So I'll try to fix that one in this PR.

**Comment by cooperka** [comment]
Yes please see the linked PR #247 with a working unit test (it's failing, in order to demonstrate the issue) 🙂 Let me know if you have questions related to it, thanks for your help!

**Comment by bhooshiek-narendiran** [comment]
Hi, @cooperka One doubt whether the view transformer should override the class transformers(parent and child) or both should execute (view transformers + class transformers)?

**Comment by cooperka** [comment]
Hmm, if both execute, is there a way to STOP the parent from executing through some syntax? If there's no way to stop it, I think it must override entirely. But I will leave that up to the library author during PR review.

**Comment by bhooshiek-narendiran** [comment]
currently, we have options to differentiate default ones(parent & child class transformers) and view transformers. So I thought, We can use view transformers if it is configured or else (parent or child class transformers) will execute. If we need to block parent class transformers alone then we need some parameter to differentiate that one.

**Comment by aarona** [comment]
Following this thread. Just wanted to chime in real quick. This might be over engineering but maybe a solution similar to how rack middleware Is implemented?
