### ISSUE TITLE
Add RuboCop To Insure Code Consistency

### ISSUE THREAD

**Issue by cguess** [procore-oss/blueprinter#231]
I'm working on adding a new feature on a fork (which I'll bring back in via a PR), but the code standards seem pretty arbitrary. What's the thoughts on adding something like [RuboCop](https://rubocop.org/) so that spacing, etc. is consistent? What the rules are doesn't really matter to me, but just nice to have something to follow.

**Comment by adamwells** [comment]
Thanks for your input! We have a Procore wide style guide we'll be adding to this repo - until then, we'll keep this issue open to track it.
