### ISSUE TITLE
Raise Error if `default_if` passed invalid value instead of eating value

### ISSUE THREAD

**Issue by cguess** [procore-oss/blueprinter#241]
When use `default_if` and an invalid symbol is passed in the key/value is just eaten and not rendered. Since there's no reason this would ever happen on purpose (that I can imagine) I'd suggest an exception be raised instead of silently failing.

This would be a breaking change, but at least it would be a loud break.

**Comment by mcclayton** [comment]
Hey @cguess, I think that definitely makes sense for the case where a symbol is explicitly passed in, but just incorrectly. I'll draft a PR for this, but this will go into a `1.0.0` release candidate branch as you correctly noted this would be a breaking change. Thanks for creating this issue!
