### ISSUE TITLE
Skip field if nil doesn't include associations which are not empty

### ISSUE THREAD

**Issue by sadda11asm** [procore-oss/blueprinter#249]
```
Blueprinter.configure do |config|
  config.if = ->(field_name, obj, _options) { obj[field_name].present? }
end
```

I am using this to not include nil fields to the response, but it also takes all associations out too.

**Comment by adamwells** [comment]
Is this with activerecord models? It's likely because the regular attributes are accessible with `[]` but associations are not - maybe try

```rb
Blueprinter.configure do |config|
  config.if = ->(field_name, obj, _options) { obj.public_send(field_name).present? }
end
```

**Comment by armandsLa** [comment]
Calling `public_send` will not work if you have custom fields in blueprint. It will throw "undefined method" error
