### ISSUE TITLE
Can I set `:root` globally?

### ISSUE THREAD

**Issue by aguynamedben** [procore-oss/blueprinter#253]
I'm migrating to Blueprinter from JBuilder. My current API always uses "items" for root. With Blueprinter I know I can use the `:root` argument while rendering to put my item(s) under a key, but is there any way to set `:root` globally? I didn't see anything in the [configuration code](https://github.com/procore/blueprinter/blob/master/lib/blueprinter/configuration.rb).

Is this a valid feature request? If I implement it would you consider it for merging?

Example:

```rb
Blueprinter.configure do |config|
  # for all renders, put the object/collection under the "items" key
  config.default_root = :items
end
```

This use case probably only makes sense if the default root value is always an array (...?)
```rb
Blueprinter.configure do |config|
  # for all renders, put the object/collection under the "items" key
  config.default_root = :items
  # ensure the value of "items" is always an array, even if an object is 
  config.default_root_force_array = true
end
```

**Comment by aguynamedben** [comment]
Maybe there's a better way to allow customization at the root level, i.e. a block I can customize right before the rendering steps. That might solve [this question](https://github.com/procore/blueprinter/issues/252) too.

```rb
Blueprinter.configure do |config|
  config.before_render do |object_or_collection, hash|
    # always put the rendered item under an 'items' key
    hash[:items] = hash

    # include Kaminari pagination at the root level
    if object_or_collection.respond_to?(:limit_value)
       hash[:page_size] = object_or_collection.limit_value
    end
    if object_or_collection.respond_to?(:current_page)
       hash[:current_page] = object_or_collection.current_page
    end
    if object_or_collection.respond_to?(:total_pages)
       hash[:last_page] = object_or_collection.total_pages
    end

    hash
  end
end
```

**Comment by Frexuz** [comment]
I would love this as well :)
