### ISSUE TITLE
Private method helpers?

### ISSUE THREAD

**Issue by Frexuz** [procore-oss/blueprinter#272]
```
class Api::V1::CountrySerializer < ActiveModel::Serializer
  attributes :name

  attribute :currency_name do
    currency&.name
  end

  attribute :currency_code do
    currency&.iso_code
  end

  private
    def currency
      @currency ||= ISO3166::Country[object.alpha2]&.currency
    end
end
```

AMS has 'global' access to `object` inside the class. 

Does blueprinter have something similar? I haven't found anything in the readme.

I've only managed to do it without lookup

```
  field :currency_name do |country|
    ISO3166::Country[country.alpha2]&.currency.name
  end

  field :currency_code do |country|
    ISO3166::Country[country.alpha2]&.currency.iso_code
  end
```

But that could be expensive in some cases.

I could also do

```
  field :currency do |country|
    c = ISO3166::Country[country.alpha2]
    {
       name: c&.name,
       code: c&.iso_code
    } 
  end
```

but i'd prefer not.., and in some cases that might not be feasible

**Comment by mcclayton** [comment]
I think to accomplish something similar in Blueprinter, you'd want something like: 

```rb
class Api::V1::CountryBlueprint < Blueprinter::Base
  field :currency_code do |object|
    currency_for(object)&.iso_code
  end

  private
  def self.currency_for(obj)
    @@currency[obj.name] ||= ISO3166::Country[obj]&.currency
  end
end
```

**Comment by kg-currenxie** [comment]
Will try later this week! Will let you know :)

**Comment by Frexuz** [comment]
Hm, getting an error

```
"exception": "#<NameError: uninitialized class variable @@currency in Api::V1::CountrySerializer\nDid you mean?  currency_for>",
```
code
```
  field :currency_code do |country|
    currency_for(country)&.iso_code
  end

  field :currency_name do |country|
    currency_for(country)&.name
  end

  private
    def self.currency_for(obj)
      @@currency[obj.alpha2] ||= ISO3166::Country[obj.alpha2]&.currency
    end
```

Not sure how to initialize it before usage? 🤔 

I also tried `@currency ||= `, but that caches it once "forever" and every subsequent call won't give me the correct value.

**Comment by sl4vr** [comment]
This should initialize correct class variable:
```ruby
@@currency = {}
```

**Comment by jasonkarns** [comment]
Agree with the desire for these kinds of helpers. Would it be possible to consider a more structural change to the API of blueprinter, to avoid the heavy use of class methods? That would make helpers more intuitive.

For instance: the recommendations above that call for defining helpers as class methods all make the mistake of presuming that `private` affects class methods. It does not.

@mcclayton / @sl4vr 
```
private
def self.currency_for(obj);end
```

This still results in `CountryBlueprint.currency_for` being a public method. I think this points to one of the huge drawbacks of using class methods and (IMO) it would be an improvement to restructure the api to use regular old instances. (The api could be made backwards compatible by making the class methods instantiate under the covers)

**Comment by kg-currenxie** [comment]
Hm, building it outside the helper like `CountryBlueprint.render(country, currency: ISO3166::Country[country.alpha2])` doesn't work for collections :)
