### ISSUE TITLE
Incorrect Transform Documentation

### ISSUE THREAD

**Issue by YSavir** [procore-oss/blueprinter#282]
The documentation for the current version (0.25.3 at time of writing) has the following instructions for `transform`:

> Whatever is returned from this transform method will end up being the resulting hash passed to serialization.

This is incorrect. The return value doesn't seem to be used at all, and any transformations need to be made on the `hash` argument directly. The example is set up correctly using `merge!`, but I assumed the focus was still on returning a the mutated hash and not on the mutation itself. This can be seen in the source code [here](https://github.com/procore/blueprinter/blob/d026b9cb863abb0fb4115803306bcd272608f646/lib/blueprinter/helpers/base_helpers.rb#L50).

**Comment by philipqnguyen** [comment]
Welcome to make a PR to update this doc
