### ISSUE TITLE
Something weird when using transform. Use case: to lower camelCase

### ISSUE THREAD

**Issue by GhaniyKie** [procore-oss/blueprinter#351]
I just using Blueprinter for my API project. I wanna transform all rendered fields as `camelCase`. Many hours i spend and found that this transform can be done using Transformer Module.

This is my transformer:

```ruby
# frozen_string_literal: true

module Transformer
  class LowerCamelCaseTransformer < Blueprinter::Transformer
    def transform(hash, _object, _options)
      hash.deep_transform_keys! { |key| key.to_s.camelize(:lower).to_sym }
    end
  end
end
```

and this module called by using `transform Transformer::LowerCamelCaseTransformer`. JSON rendered as well, but something weird happened (for me).

When i use `ModelBlueprinter.render(data, view: :view)` for my `association`, only *associated model* transformed to lower camelCase, atrribute defined using `fields` or `field :field { block }` doesn't transformed.

**Using *view block* with association defined inside it** <`view :view { association foo, blueprint: FooBlueprint }`>

```json
{
    "data": {
        "id": 7,
        "category": null,
        "created_at": "2023-10-22T07:20:53+07:00",
        "description": null,
        "files_attachments": [
            {
                "id": 9,
                "byteSize": 20480,
                "checksum": "LrbjFKInVDT6U9mFq+4OGg==",
                "contentType": "application/x-tar",
                "createdAt": "2023-10-22T07:20:53+07:00",
                "filename": "ghany.tar",
                "url": "/rails/active_storage/blobs/redirect/ey.....bfbf9c07e/ghany.tar"
            }
          ]
     }
}
```

**Without *view block*, buat association still defined in blueprint class**

```json
{
    "data": {
        "id": 7,
        "category": null,
        "createdAt": "2023-10-22T07:20:53+07:00",
        "description": null,
        "filesAttachments": [
            {
                "id": 9,
                "byteSize": 20480,
                "checksum": "LrbjFKInVDT6U9mFq+4OGg==",
                "contentType": "application/x-tar",
                "createdAt": "2023-10-22T07:20:53+07:00",
                "filename": "ghany.tar",
                "url": "/rails/active_storage/blobs/redirect/ey.....bfbf9c07e/ghany.tar"
            }
          ]
     }
}
```

**Association defined inside *view block* but view not called when rendering inside Controller**. <`ModelBlueprinter.render(data)`>

```json
{
    "data": {
        "id": 7,
        "category": null,
        "createdAt": "2023-10-22T07:20:53+07:00",
        "description": null
     }
}
```

Also, as per documented, `meta` option could be rendered as JSON. But, when i define it, this meta option doesn't transformed.

Because of this, monkey patch to `self.render` implemented to my `ApplicationBlueprinter < Blueprinter::Base` class.

```ruby
  def self.render(object, options = {})
    # Monkey patch to automatically define :data as the root key
    options = options.merge(root: :data)

    # Automatically transform metadata keys to lower camel case
    options[:meta].deep_transform_keys! { |key| key.to_s.camelize(:lower).to_sym } if options[:meta]&.any?

    super(object, options)
  end
```

Can you help me, please?

**Comment by ritikesh** [comment]
hi @GhaniyKie

As far as I can tell, the transformation happens only on the blueprint's views and not on the options passed or on the associations - you can specify the transformer on the associated blueprint itself, which should be respected. Hence, the transformation might/will not reflect. This has to be taken care of by the implementer as it might not be obvious on which `transformer` to use in both the cases (there could be several of them during the scope of a single blueprint render call).

Hope this helps. If either of these does not work for you, please share a sample application and the blueprint class for us to debug this further?
