### ISSUE TITLE
lazy load for association

### ISSUE THREAD

**Issue by zgid123** [procore-oss/blueprinter#359]
Hi,

I wanna skip association if I don't eager load it. The association extractor does not support it at the moment I guess.

I wonder what is the correct way to do the lazy load for blue printer?

Thanks.

**Comment by jhollinger** [comment]
The feature request I read here is _optional associations_. Blueprinter already has optional fields via `if:` and `unless:`, and it seems reasonable that associations should have the same.

Rails already has a way to detect if associations are eager loaded. So **if** Blueprinter adds `if`/`unless` options for associations, it could be done like this:

```ruby
class WidgetBlueprinter < Blueprinter::Base
  association :category, if: ->(_field, widget, _opts) {
    widget.association(:category).loaded?
  }
end
```

**Comment by zgid123** [comment]
Thanks for your answer. But I think I will monkey patch the extractor because if we use that approach, every association needs the condition

**Comment by ritikesh** [comment]
@zgid123 this is outside of the scope of Blueprinter and has been discussed already in #294. Although blueprinter might open up avenues to assist it, it would not support it natively. Pls follow discussions around #341 / #357 for future scopes.
