### ISSUE TITLE
Render one blueprint inside another?

### ISSUE THREAD

**Issue by shayani** [procore-oss/blueprinter#365]
Is it possible to, when generating a blueprint called B, include all data from another blueprint (called A)?

It would have the same effect of 
```
BluePrinterA.render(a_object).merge(BluePrinterB.render(b_object)
```

but I would like to be coded like this:
```
BluePrinterA < BluePrinter::Base
  field :name
end 

BluePrinterB < BluePrinter::Base
  BluePrinterA.render(a_object)
  field :last_name 
end
```

(since A and B are two different objects, a view would not be useful...)

**Comment by jhollinger** [comment]
I don't believe there's specific support for that, but you could accomplish the same thing with a plain Ruby module. Would work for views, too.

```ruby
module MySharedBlueprintDefs
  def self.extended(blueprint)
    blueprint.class_eval do
      fields :foo, ...

      view :extended do
         fields ...
      end
    end
  end
end

class BlueprinterA < Blueprinter::Base
  extend MySharedBlueprintDefs
  fields ...
end

class BlueprinterB < Blueprinter::Base
  extend MySharedBlueprintDefs
  fields ...
end
```

Both `BlueprinterA` and `BlueprinterB` would have all fields, associations, and views defined in `MySharedBlueprintDevs`.

**Comment by shayani** [comment]
Thanks! That's an elegant solution.
