### ISSUE TITLE
Is there a way to exclude fields and associations and pass/process a block

### ISSUE THREAD

**Issue by marvfinsy** [procore-oss/blueprinter#374]
Trying to use dynamic fields and/or dynamic associations. But i need to be able to include/exclude that column. So i'm trying to use the field exclusion (using lambda) along with processing a block.

Is there a way to do this?

~Marvin

**Comment by ritikesh** [comment]
@marvfinsy, it would be helpful to have a look at your blueprint and the expected output visually to be able to suggest a way forward.
