### ISSUE TITLE
[bug] config.sort_fields_by = :definition causes SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by matthiasmllnr** [procore-oss/blueprinter#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a regression?

- [ ] Yes, this used to work before

### Current Behavior

When i call `.render_as_json(<model_instance>, view: :default)` with this config: 
`Blueprinter.configure do |config|
  config.sort_fields_by = :definition
end`
I get: 
SystemStackError: stack level too deep
from /usr/local/bundle/gems/blueprinter-1.0.2/lib/blueprinter/view_collection.rb:87:in `block in add_to_ordered_fields'

### Expected Behavior

The created json is supposed to be sorted by fields definition. Instead a SystemStackError occurs.

### Steps To Reproduce

1. Use this config: `Blueprinter.configure do |config|
  config.sort_fields_by = :definition
end`
2. call render on a Blueprint

### Environment

```markdown
- OS: macOS 13.2.1
- Ruby Version: 3.2.3
```

**Comment by PaulAshraf** [comment]
Can you provide a minimal example to be able to reproduce the bug
I was not able to recreate it on a fresh `rails new` project with blueprinter

**Comment by jhollinger** [comment]
I can't reproduce it either. Can you find the exact version of blueprinter where this behavior starts?
