### ISSUE TITLE
[Question/Support] Set one view as the default view

### ISSUE THREAD

**Issue by araccaine** [procore-oss/blueprinter#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Question

Is there something like a "default view" that I can set when using an `association`?

Currently, I also have to specify an association with an explicit view:

```ruby
association :sections, blueprint: SectionBlueprint, view: :normal
```

## Example

```ruby
# The base serializer, e.g. chapters of a book
class ChapterBlueprint < Blueprinter::Base
  identifier :id

  view :normal do
    fields :name, :description
  end

  view :extended do
    include_view :normal

    association :sections, blueprint: SectionBlueprint # Here I have to write view: :normal, otherwise it only renders the section's :id
  end
end

# Each chapter has 0 to n sections
class SectionBlueprint < Blueprinter::Base
  identifier :id

  view :normal do
    fields :name, :page_ref
  end

  view :extended do
    include_view :normal

    fields :created_at, :updated_at
  end
end
```

## What I am looking for

Something like this:

```ruby
Blueprinter.configure do |config|
  config.default_view = :normal
end
```

**Comment by ritikesh** [comment]
Hi @araccaine, whatever you define at the root level, automatically already becomes your `default` view. So you could still achieve this with - 
```
# The base serializer, e.g. chapters of a book
class ChapterBlueprint < Blueprinter::Base
  identifier :id
  fields :name, :description

  view :extended do
    association :sections, blueprint: SectionBlueprint # Here I have to write view: :normal, otherwise it only renders the section's :id
  end
end

# Each chapter has 0 to n sections
class SectionBlueprint < Blueprinter::Base
  identifier :id
  fields :name, :page_ref

  view :extended do
    fields :created_at, :updated_at
  end
end
```
Let me know if that helps!

**Comment by araccaine** [comment]
Thank you very much for your detailed answer!

Now after reading my own code and this issue again after a few weeks I see that my question was not what I intended to achieve. What I really need is:

- The `:extended` view would be the default view
- The `:normal` view (with less information/fields) would be used only for special occasions.
 
A better naming may be something like `:detailed` and `:simple`, where `:detailed` is the default view with more fields. For the other way round (like my first question was worded) your suggestion would work. But having more fields in the "default view" would not work.
