### ISSUE TITLE
[bug] V 1.0.2 - Issue with Association  when including custom name

### ISSUE THREAD

**Issue by Z-GH** [procore-oss/blueprinter#411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a regression?

- [X] Yes, this used to work before

### Current Behavior

We have Rails 7.0 and Blueprinter 1.0.1, and we used to use association with custom name, it was working as expected. However, bump to Rails 7.1 and update all other gems, including Blueprinter, which is V 1.0.2, had an issue with associations and custom names to raise an exception as 
```ruby
ActiveRecord::AssociationNotFoundError:
       Association named 'custom_name' was not found on Classxx; perhaps you misspelled it?
```
The issue that when we call `blueprint.reflections[view].associations` inside override `pre_render` method, the hash came with key for display_name instead of actual association name, which through the exception.

### Expected Behavior

If we reverse to old version of Blueprinter, all work as expected

### Steps To Reproduce

- Upgrade to V 1.0.2
- Create a serializer with association
```ruby
association :class_1, name: :class_2, blueprint: Class1Serializer do |object|
    ....
  end
```

### Environment

```markdown
- OS: Mac
- Browser Name and version: Chrome Or we can replicated from console terminal
- Ruby Version: 7.1.2.3
```

**Comment by lessthanjacob** [comment]
Hey @Z-GH! Thanks for reporting!

> The issue that when we call blueprint.reflections[view].associations inside override pre_render method, the hash came with key for display_name instead of actual association name, which through the exception.

Could you add a simple version of your custom `pre_render` code that throws the exception when you get a moment?

**Comment by Z-GH** [comment]
Thanks @lessthanjacob , we can do, I was hoping if we can change the gem itself for versioning consistency. However, that works as well.
Thank you.
