### ISSUE TITLE
Run blueprint generator whith another generator commands in Rails.

### ISSUE THREAD

**Issue by a-chacon** [procore-oss/blueprinter#431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Is just for make the creation of a project easier.

### Describe the feature you'd like to see implemented

I would like to run something like `rails g scaffold teacher name:string email:string` and after all rails generators, run the blueprint generator too.

Something like this:
```bash
 rails g scaffold teacher name:string email:string
      invoke  active_record
      create    db/migrate/20240624222343_create_teachers.rb
      create    app/models/teacher.rb
      create    app/blueprints/teacher_blueprint.rb            <-------------------- HERE
      invoke    test_unit
      create      test/models/teacher_test.rb
      invoke      factory_bot
      create        test/factories/teachers.rb
      invoke  resource_route
       route    resources :teachers
      invoke  scaffold_controller
      create    app/controllers/teachers_controller.rb
      invoke    resource_route
      invoke    test_unit
      create      test/controllers/teachers_controller_test.rb

```

### Describe alternatives you've considered

Just run `rails g blueprinter:blueprint teacher`

**Comment by lessthanjacob** [comment]
Hey Andrés! Thanks for opening this. 

We're thinking of moving the existing generator code outside of the this repository, and include it in [blueprinter-activerecord](https://github.com/procore-oss/blueprinter-activerecord) instead. After we make a decision there, we can investigate the lift for including a Railtie that can provide this functionality.
