### ISSUE TITLE
[bug] :view key being deleted from options hash by #render

### ISSUE THREAD

**Issue by ryanmccarthypdx** [procore-oss/blueprinter#451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a regression?

- [ ] Yes, this used to work before

### Current Behavior

It seems that the process of rendering is deleting the `:view` key from the options hash.  This breaks batching as only the first batch can be rendered correctly with subsequent ones falling back to the default view.

### Expected Behavior

Options k-v pairs should persist through to subsequent batch renders.

### Steps To Reproduce

Given this blueprint:
```
class FooBlueprint < ApplicationBlueprint
  identifier :id

  view :with_bar_id do
    field :bar_id
  end
end
```
This code:
```
options = { a_key: 'a value', view: :with_bar_id }
prerendered_foos = []
Foo.limit(5).in_batches(of: 2) do |batch|
  prerendered_foos += FooBlueprint.render_as_hash(batch, options)
end
```
generates this as `prerendered_foos`:
```
[
  {:id=>1, :bar_id=>101},
  {:id=>2, :bar_id=>102},
  {:id=>3},
  {:id=>4},
  {:id=>5}
]
```
The rendering of the first batch deletes the view option and the subsequent batches fall back to the default identifier-only view.

The workaround I am currently using is to re-add the view to the options hash after every batch, but this is unsatisfactory.  

### Environment

```markdown
- OS: OSX 14.4.1
- Browser Name and version: N/A
- Ruby Version: 3.2.4
```

**Comment by jhollinger** [comment]
FWIW [this looks like a good candidate to me](https://github.com/procore-oss/blueprinter/blame/ce1666ed7009c974f938bf6f1943467cd6e6bcff/lib/blueprinter/helpers/base_helpers.rb#L18), although it's five years old. But if your options hash is _newly_ being shared across multiple renders, it seems a likely cause.

**Comment by ryanmccarthypdx** [comment]
Ah, apologies, I could have sworn this was working before and I saw [this recent change in base.rb](https://github.com/procore-oss/blueprinter/blame/ce1666ed7009c974f938bf6f1943467cd6e6bcff/lib/blueprinter/base.rb#L159) and thought that was the culprit.

The code that @jhollinger references above is indeed the issue, so this is perhaps more of a 'feature request'.

I have this [draft PR (currently without tests)](https://github.com/procore-oss/blueprinter/pull/453) that would be a possible 'fix' for this if we agree this is a good idea.  I'm not really sure why the existing uses `delete` but perhaps someone has a good reason.
