### ISSUE TITLE
[bug] A view key of nil is not using the default

### ISSUE THREAD

**Issue by nickjer** [procore-oss/blueprinter#471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a regression?

- [X] Yes, this used to work before

### Current Behavior

Previously (in v1.1.0) the following worked...

```ruby
MyBlueprint.render_as_json(my_object, view: nil)
```

Now (in v1.1.1) it raises with the exception...

```ruby
#<Blueprinter::BlueprinterError: View '' is not defined>
```

I believe it was introduced when the following line was introduced:

https://github.com/procore-oss/blueprinter/blob/0e7f160d55e9f8cf53035f74af04bb33e6b739da/lib/blueprinter/helpers/base_helpers.rb#L18

Previously it was...

```ruby
view_name = options.delete(:view) || :default
```

A possible solution is...

```ruby
view_name = options[:view] || :default
```

### Environment

```markdown
- OS: Linux
- Browser Name and version: *
- Ruby Version: 3.3.4
```

**Comment by lessthanjacob** [comment]
Thanks for opening the issue @nickjer! Was able to reproduce via test, and working on a quick fix!
